sudo: required
services:
  - docker

  before_install:
    -  docker build -t nelsoncastro/docker-react -f Dockerfile.dev .

  script:
    - docker run -e CI=true nelsoncastro/docker-react npm run test